# Generated by Django 5.2.4 on 2025-07-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('more_info', models.TextField(blank=True, null=True)),
                ('proof_files', models.FileField(blank=True, null=True, upload_to='proofs/')),
                ('crime_datetime', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='New', max_length=50)),
            ],
        ),
    ]
